### ISSUE TITLE
Use PlantUml in building the initial threat model

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/p-threat-model-graph-visualisation#1]
Replicate the image below with PlantUml

Reference: 
- https://github.com/filetrust/OSBot-jira/tree/master/OSBot-GraphDB/osbot_graphsv
- https://www.slideshare.net/DinisCruz/map-camp-why-context-is-your-crown-jewels-wardley-maps-and-threat-modeling

![map-camp-why-context-is-your-crown-jewels-wardley-maps-and-threat-modeling-14-638.jpg](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/18d08a64-b369-433d-9b1a-d62bf0d50f35)

**Comment by baker371** [comment]
![model 1](https://user-images.githubusercontent.com/8102313/96301854-79890780-1000-11eb-80e2-91f190c95641.png)

**Comment by baker371** [comment]
![plantuml](https://user-images.githubusercontent.com/8102313/96365538-f7a4f580-1149-11eb-9202-e4d111574253.png)

**Comment by baker371** [comment]
![model 1](https://user-images.githubusercontent.com/8102313/96376673-078ffa00-1189-11eb-91cb-a366f9775b9c.png)

**Comment by baker371** [comment]
![model 3](https://user-images.githubusercontent.com/8102313/96376687-1d052400-1189-11eb-93dc-829d44c93631.png)

**Comment by baker371** [comment]
![plantuml 4](https://user-images.githubusercontent.com/8102313/97110406-3c9ccf00-16ea-11eb-9ff3-d4575fc757bf.png)

**Comment by baker371** [comment]
![plantuml 5](https://user-images.githubusercontent.com/8102313/97111721-8806ab80-16f1-11eb-8315-98a1b25e7fb8.png)
