### ISSUE TITLE
Extract sheet information into json format for PlantUml consumption

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/p-threat-model-graph-visualisation#11]
**Workflow:**
1. Extract information from google or excel sheet
2. Convert the extracted information to json format
3. Import json information to PlantUml

**Comment by baker371** [comment]
@chrisdiao now that I have the graph into a dataframe, it is easy to create a json file, I just need specifications on how @lucia15 needs the json file nested, or arranged then I can go ahead to create the json file.

**Comment by chrisdiao** [comment]
thanks for the update @baker371
