### ISSUE TITLE
Create a MD documentation in setting up the EC2 instance environment 

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/p-threat-model-graph-visualisation#28]

**Comment by baker371** [comment]
![ec1](https://user-images.githubusercontent.com/8102313/102121329-e419c080-3e54-11eb-8d16-cb451249f87a.png)

**Comment by baker371** [comment]
![ec2](https://user-images.githubusercontent.com/8102313/102122138-20015580-3e56-11eb-8ad2-d4db87d4a3fc.png)

**Comment by baker371** [comment]
![ec3](https://user-images.githubusercontent.com/8102313/102125704-22b27980-3e5b-11eb-98b6-0878d29b8877.png)

**Comment by baker371** [comment]
![ec4](https://user-images.githubusercontent.com/8102313/102126364-06fba300-3e5c-11eb-85d1-4c0af1244fd8.png)

**Comment by baker371** [comment]
![ec5](https://user-images.githubusercontent.com/8102313/102126953-dd8f4700-3e5c-11eb-8864-3492317afa5d.png)

**Comment by baker371** [comment]
![ec6](https://user-images.githubusercontent.com/8102313/102128187-8d18e900-3e5e-11eb-8a96-34e35c3afc84.png)

**Comment by baker371** [comment]
![ec7](https://user-images.githubusercontent.com/8102313/102129035-d0278c00-3e5f-11eb-9657-2b12b3c87fce.png)
