### ISSUE TITLE
Replicate the images using PlantUml

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/p-threat-model-graph-visualisation#8]
- Break the diagrams into separate files
- Start exploring a better design for users to easily consume the diagram. E.g. Use of icons
- Create a folder for experiments
- Separate the plantuml file for the color code mapping
- Maximize the use of import

![image_1.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/f52933f4-3d04-41ba-8285-dcbfbcfe040e)
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/ae84c5cf-7bb8-4dda-af75-974753c30878)
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5f43cee726e80382e54a0b0f/88df3f6d-8d21-4c8c-8c5a-317eb4ca98c7)

**Comment by baker371** [comment]
@chrisdiao I will utilize all types of icons, as you can see I am including more with every model, code has been added. Let me try now to integrate importation
