### ISSUE TITLE
Replicate the  EMMA Dataport wardley map into PlantUml

### ISSUE THREAD

**Issue by chrisdiao** [k8-proxy/p-threat-model-graph-visualisation#9]
Once done send PR to https://github.com/k8-proxy/gp-emma-dataport-website

![image](https://user-images.githubusercontent.com/68153062/98021168-f01a6780-1e3e-11eb-9048-358f9ec9372e.png)

**Comment by baker371** [comment]
@chrisdiao after thorough tryouts and investigations, I have come to a conclusion that PlantUML is NOT suitable to draw Wardley Maps, the good news is that I have Identified and now experimenting with tools that are created specifically to draw Wardley maps as code.
